2024-04-25 17:34:05,170 - INFO - Item: {"func_name": "dd_get_item_size", "func_src_before": "long dd_get_item_size(struct dump_dir *dd, const char *name)\n{\n    long size = -1;\n    char *iname = concat_path_file(dd->dd_dirname, name);\n    struct stat statbuf;\n\n    if (lstat(iname, &statbuf) == 0 && S_ISREG(statbuf.st_mode))\n        size = statbuf.st_size;\n    else\n    {\n        if (errno == ENOENT)\n            size = 0;\n        else\n            perror_msg(\"Can't get size of file '%s'\", iname);\n    }\n\n    free(iname);\n\n    return size;\n}", "func_src_after": "long dd_get_item_size(struct dump_dir *dd, const char *name)\n{\n    if (!str_is_correct_filename(name))\n        error_msg_and_die(\"Cannot get item size. '%s' is not a valid file name\", name);\n\n    long size = -1;\n    char *iname = concat_path_file(dd->dd_dirname, name);\n    struct stat statbuf;\n\n    if (lstat(iname, &statbuf) == 0 && S_ISREG(statbuf.st_mode))\n        size = statbuf.st_size;\n    else\n    {\n        if (errno == ENOENT)\n            size = 0;\n        else\n            perror_msg(\"Can't get size of file '%s'\", iname);\n    }\n\n    free(iname);\n\n    return size;\n}", "line_changes": {"deleted": [], "added": [{"line_no": 3, "char_start": 63, "char_end": 103, "line": "    if (!str_is_correct_filename(name))\n"}, {"line_no": 4, "char_start": 103, "char_end": 191, "line": "        error_msg_and_die(\"Cannot get item size. '%s' is not a valid file name\", name);\n"}, {"line_no": 5, "char_start": 191, "char_end": 192, "line": "\n"}]}, "char_changes": {"deleted": [], "added": [{"char_start": 67, "char_end": 196, "chars": "if (!str_is_correct_filename(name))\n        error_msg_and_die(\"Cannot get item size. '%s' is not a valid file name\", name);\n\n    "}]}, "commit_link": "github.com/abrt/libreport/commit/239c4f7d1f47265526b39ad70106767d00805277", "file_name": "src/lib/dump_dir.c", "vul_type": "cwe-022"}
2024-04-25 19:38:12,717 - ERROR - An error occurred when calling openai endpoint: 'prompt.json' is not of type 'object' - 'messages.0'
2024-04-25 19:38:41,336 - ERROR - An error occurred when calling openai endpoint: 'prompt.json' is not of type 'object' - 'messages.0'
2024-04-25 19:39:29,650 - ERROR - An error occurred when calling openai endpoint: 'prompt.json' is not of type 'object' - 'messages.0'
2024-04-25 19:39:42,705 - ERROR - An error occurred when calling openai endpoint: None is not of type 'object' - 'messages.1'
